### ISSUE TITLE
add ui feedback when "create playlist" button is clicked

### ISSUE THREAD

**Issue by raspberri05** [raspberri05/tunestats#39]
there should be a loading symbol and then it should briefly display something to indicate that the playlist has been successfully created

**Comment by PranjalDby** [comment]
i unable to run the page it says cannot GET /

**Comment by DDweeb** [comment]
The button has no functionality

**Comment by raspberri05** [comment]
Hi, did you run npm install inside the app/api directory? I think I may have forgotten to add that to the setup instructions. Assuming everything is set up, the button will cause a playlist to be created in the logged in spotify account. Currently, nothing visible will happen in the UI upon clicking the button.

**Comment by PranjalDby** [comment]
yeah i run all the steps

**Comment by PranjalDby** [comment]
seems like 
app
.use(express.static(__dirname + "/")) ==> missing some files
.use(cors()).use(cookieParser());

**Comment by raspberri05** [comment]
What node version are you using?

**Comment by PranjalDby** [comment]
node version 16

**Comment by raspberri05** [comment]
I've set up the project using node 20.15.0, so trying to use that may work. I must've forgotten to put that in the documentation. If you want to have multiple versions of node set up you can use something like nvm or volta, otherwise you can just update your version of node to 20.15.0. If that doesn't work, I would recommend checking your spotify app configuration in the spotify developer dashboard to ensure that the correct callback uris are set and that the allowed users are set to allow the spotify account you are logging into tunestats with to access the spotify dev app.

**Comment by PranjalDby** [comment]
ok.. beacause i tried everyhing changing port,etc

**Comment by raspberri05** [comment]
ok yeah i would try changing the node version to 20.15.0. I can try taking a closer look at the code tomorrow if that doesn't work to see if i missed a setup step

**Comment by PranjalDby** [comment]
ok
